// <auto-generated />
namespace LTTTBaiTapLon671.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Manager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Manager));
        
        string IMigrationMetadata.Id
        {
            get { return "202203090518461_Manager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
