// <auto-generated />
namespace LTTTBaiTapLon671.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QLtram2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QLtram2));
        
        string IMigrationMetadata.Id
        {
            get { return "202205301520353_QLtram2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
